plugin: amazon.aws.aws_ec2
boto_profile: "{{ lookup('env', 'AWS_PROFILE') }}"

regions:
  - "{{ lookup('env', 'AWS_REGION') }}"

filters:
  tag:InstanceName: "{{ lookup('env', 'INSTANCE_NAME') }}"
  tag:SecurityScans: true

keyed_groups:
  - key: tags
    prefix: tag
    separator: "_"

hostnames: private-ip-address
