plugin: amazon.aws.aws_ec2
boto_profile: finance-staging-eu-west-2

regions:
  - eu-west-2

filters:
  tag:Environment: staging
  tag:Service: e5
  tag:ServiceSubType: e5-fin-v2

keyed_groups:
  - key: tags
    prefix: tag
    separator: "_"

hostnames: private-ip-address
